services:
  db:
    image: postgres:15-alpine
    container_name: academy_db_container
    environment:
      POSTGRES_DB: academy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/03-seed.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/04-roles.sql