version: '3.8'

services:  
  db:     
    image: postgres:15-alpine
    container_name: academy_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: academy_db
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: academy_web_container
    ports:
      - "3000:3000"
    environment:
      HOSTNAME: "0.0.0.0" 
      DATABASE_URL: "postgresql://app:${DB_APP_PASSWORD}@db:5432/academy_db"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next         